# Generated by Django 4.2.11 on 2024-05-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0002_chatmessage_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
