# Generated by Django 4.2.11 on 2024-05-18 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0003_chatmessage_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='file_type',
        ),
    ]
